// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: dept.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleDeptTreeSelectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId int32 `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
}

func (x *RoleDeptTreeSelectRequest) Reset() {
	*x = RoleDeptTreeSelectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDeptTreeSelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeptTreeSelectRequest) ProtoMessage() {}

func (x *RoleDeptTreeSelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeptTreeSelectRequest.ProtoReflect.Descriptor instead.
func (*RoleDeptTreeSelectRequest) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{0}
}

func (x *RoleDeptTreeSelectRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RoleDeptTreeSelectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckedKeys []int32      `protobuf:"varint,1,rep,packed,name=checkedKeys,proto3" json:"checkedKeys,omitempty"`
	Depts       []*DeptLabel `protobuf:"bytes,2,rep,name=depts,proto3" json:"depts,omitempty"`
}

func (x *RoleDeptTreeSelectReply) Reset() {
	*x = RoleDeptTreeSelectReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleDeptTreeSelectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeptTreeSelectReply) ProtoMessage() {}

func (x *RoleDeptTreeSelectReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeptTreeSelectReply.ProtoReflect.Descriptor instead.
func (*RoleDeptTreeSelectReply) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{1}
}

func (x *RoleDeptTreeSelectReply) GetCheckedKeys() []int32 {
	if x != nil {
		return x.CheckedKeys
	}
	return nil
}

func (x *RoleDeptTreeSelectReply) GetDepts() []*DeptLabel {
	if x != nil {
		return x.Depts
	}
	return nil
}

type DeptLabel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Children []*DeptLabel `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	DeptId   int32        `protobuf:"varint,2,opt,name=deptId,proto3" json:"deptId,omitempty"`
	DeptName string       `protobuf:"bytes,3,opt,name=deptName,proto3" json:"deptName,omitempty"`
}

func (x *DeptLabel) Reset() {
	*x = DeptLabel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeptLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptLabel) ProtoMessage() {}

func (x *DeptLabel) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptLabel.ProtoReflect.Descriptor instead.
func (*DeptLabel) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{2}
}

func (x *DeptLabel) GetChildren() []*DeptLabel {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *DeptLabel) GetDeptId() int32 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *DeptLabel) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

type ListDeptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeptName string `protobuf:"bytes,1,opt,name=deptName,proto3" json:"deptName,omitempty"`
	Status   int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	DeptId   int64  `protobuf:"varint,3,opt,name=deptId,proto3" json:"deptId,omitempty"`
}

func (x *ListDeptRequest) Reset() {
	*x = ListDeptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDeptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeptRequest) ProtoMessage() {}

func (x *ListDeptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeptRequest.ProtoReflect.Descriptor instead.
func (*ListDeptRequest) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{3}
}

func (x *ListDeptRequest) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *ListDeptRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListDeptRequest) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

type ListDeptReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DeptTree `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListDeptReply) Reset() {
	*x = ListDeptReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDeptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeptReply) ProtoMessage() {}

func (x *ListDeptReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeptReply.ProtoReflect.Descriptor instead.
func (*ListDeptReply) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{4}
}

func (x *ListDeptReply) GetData() []*DeptTree {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetDeptTreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeptName string `protobuf:"bytes,1,opt,name=deptName,proto3" json:"deptName,omitempty"`
	Status   int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	DeptId   int64  `protobuf:"varint,3,opt,name=deptId,proto3" json:"deptId,omitempty"`
}

func (x *GetDeptTreeRequest) Reset() {
	*x = GetDeptTreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeptTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeptTreeRequest) ProtoMessage() {}

func (x *GetDeptTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeptTreeRequest.ProtoReflect.Descriptor instead.
func (*GetDeptTreeRequest) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeptTreeRequest) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *GetDeptTreeRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetDeptTreeRequest) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

type GetDeptTreeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DeptTree `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetDeptTreeReply) Reset() {
	*x = GetDeptTreeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeptTreeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeptTreeReply) ProtoMessage() {}

func (x *GetDeptTreeReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeptTreeReply.ProtoReflect.Descriptor instead.
func (*GetDeptTreeReply) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{6}
}

func (x *GetDeptTreeReply) GetData() []*DeptTree {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateDeptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentId int64  `protobuf:"varint,1,opt,name=parentId,proto3" json:"parentId,omitempty"`
	DeptName string `protobuf:"bytes,2,opt,name=deptName,proto3" json:"deptName,omitempty"`
	Leader   string `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Phone    string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email    string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status   int32  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Sort     int32  `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *CreateDeptRequest) Reset() {
	*x = CreateDeptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDeptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeptRequest) ProtoMessage() {}

func (x *CreateDeptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeptRequest.ProtoReflect.Descriptor instead.
func (*CreateDeptRequest) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDeptRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CreateDeptRequest) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *CreateDeptRequest) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *CreateDeptRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateDeptRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateDeptRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateDeptRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CreateDeptReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDeptReply) Reset() {
	*x = CreateDeptReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDeptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeptReply) ProtoMessage() {}

func (x *CreateDeptReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeptReply.ProtoReflect.Descriptor instead.
func (*CreateDeptReply) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{8}
}

type UpdateDeptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeptId   int64  `protobuf:"varint,1,opt,name=deptId,proto3" json:"deptId,omitempty"`
	ParentId int64  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	DeptName string `protobuf:"bytes,3,opt,name=deptName,proto3" json:"deptName,omitempty"`
	Leader   string `protobuf:"bytes,4,opt,name=leader,proto3" json:"leader,omitempty"`
	Phone    string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email    string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Status   int64  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Sort     int32  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
}

func (x *UpdateDeptRequest) Reset() {
	*x = UpdateDeptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDeptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeptRequest) ProtoMessage() {}

func (x *UpdateDeptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeptRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeptRequest) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDeptRequest) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *UpdateDeptRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UpdateDeptRequest) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *UpdateDeptRequest) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *UpdateDeptRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateDeptRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateDeptRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateDeptRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type UpdateDeptReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDeptReply) Reset() {
	*x = UpdateDeptReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDeptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeptReply) ProtoMessage() {}

func (x *UpdateDeptReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeptReply.ProtoReflect.Descriptor instead.
func (*UpdateDeptReply) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{10}
}

type DeleteDeptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDeptRequest) Reset() {
	*x = DeleteDeptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDeptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeptRequest) ProtoMessage() {}

func (x *DeleteDeptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeptRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeptRequest) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDeptRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDeptReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDeptReply) Reset() {
	*x = DeleteDeptReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dept_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDeptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeptReply) ProtoMessage() {}

func (x *DeleteDeptReply) ProtoReflect() protoreflect.Message {
	mi := &file_dept_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeptReply.ProtoReflect.Descriptor instead.
func (*DeleteDeptReply) Descriptor() ([]byte, []int) {
	return file_dept_proto_rawDescGZIP(), []int{12}
}

var File_dept_proto protoreflect.FileDescriptor

var file_dept_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x65, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x19, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x70, 0x74,
	0x54, 0x72, 0x65, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x6a, 0x0a, 0x17, 0x52, 0x6f, 0x6c,
	0x65, 0x44, 0x65, 0x70, 0x74, 0x54, 0x72, 0x65, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x4b,
	0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x65, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x2d, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x05,
	0x64, 0x65, 0x70, 0x74, 0x73, 0x22, 0x74, 0x0a, 0x09, 0x44, 0x65, 0x70, 0x74, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x33, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x08, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x70, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5d, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x54, 0x72, 0x65,
	0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x60, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x70, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x70, 0x74, 0x54, 0x72, 0x65, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x54,
	0x72, 0x65, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xbb, 0x01, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xd3, 0x01, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x64, 0x65, 0x70, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x70, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x6f, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x22, 0x11, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xa9, 0x05, 0x0a, 0x04,
	0x44, 0x65, 0x70, 0x74, 0x12, 0x61, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x70, 0x74,
	0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x64, 0x65,
	0x70, 0x74, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x6e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x70, 0x74, 0x54, 0x72, 0x65, 0x65, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x54, 0x72, 0x65,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x74, 0x54,
	0x72, 0x65, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17,
	0x12, 0x15, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x74, 0x2f, 0x64,
	0x65, 0x70, 0x74, 0x54, 0x72, 0x65, 0x65, 0x12, 0x65, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x70, 0x74, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a,
	0x22, 0x0c, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x74, 0x12, 0x65,
	0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x12, 0x1f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a, 0x1a, 0x0c, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2f, 0x64, 0x65, 0x70, 0x74, 0x12, 0x67, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x65, 0x70, 0x74, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x2a, 0x11, 0x2f, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x74, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x96,
	0x01, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x70, 0x74, 0x54, 0x72, 0x65, 0x65, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x65, 0x70, 0x74, 0x54, 0x72, 0x65,
	0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x44, 0x65, 0x70, 0x74, 0x54, 0x72, 0x65, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x30, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2a, 0x12, 0x28, 0x2f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x64, 0x65, 0x70, 0x74, 0x2f, 0x72, 0x6f, 0x6c, 0x65,
	0x44, 0x65, 0x70, 0x74, 0x54, 0x72, 0x65, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x2f, 0x7b,
	0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x7d, 0x42, 0x19, 0x5a, 0x17, 0x66, 0x65, 0x6e, 0x67, 0x79,
	0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dept_proto_rawDescOnce sync.Once
	file_dept_proto_rawDescData = file_dept_proto_rawDesc
)

func file_dept_proto_rawDescGZIP() []byte {
	file_dept_proto_rawDescOnce.Do(func() {
		file_dept_proto_rawDescData = protoimpl.X.CompressGZIP(file_dept_proto_rawDescData)
	})
	return file_dept_proto_rawDescData
}

var file_dept_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dept_proto_goTypes = []interface{}{
	(*RoleDeptTreeSelectRequest)(nil), // 0: api.admin.v1.RoleDeptTreeSelectRequest
	(*RoleDeptTreeSelectReply)(nil),   // 1: api.admin.v1.RoleDeptTreeSelectReply
	(*DeptLabel)(nil),                 // 2: api.admin.v1.DeptLabel
	(*ListDeptRequest)(nil),           // 3: api.admin.v1.ListDeptRequest
	(*ListDeptReply)(nil),             // 4: api.admin.v1.ListDeptReply
	(*GetDeptTreeRequest)(nil),        // 5: api.admin.v1.GetDeptTreeRequest
	(*GetDeptTreeReply)(nil),          // 6: api.admin.v1.GetDeptTreeReply
	(*CreateDeptRequest)(nil),         // 7: api.admin.v1.CreateDeptRequest
	(*CreateDeptReply)(nil),           // 8: api.admin.v1.CreateDeptReply
	(*UpdateDeptRequest)(nil),         // 9: api.admin.v1.UpdateDeptRequest
	(*UpdateDeptReply)(nil),           // 10: api.admin.v1.UpdateDeptReply
	(*DeleteDeptRequest)(nil),         // 11: api.admin.v1.DeleteDeptRequest
	(*DeleteDeptReply)(nil),           // 12: api.admin.v1.DeleteDeptReply
	(*DeptTree)(nil),                  // 13: api.admin.v1.DeptTree
}
var file_dept_proto_depIdxs = []int32{
	2,  // 0: api.admin.v1.RoleDeptTreeSelectReply.depts:type_name -> api.admin.v1.DeptLabel
	2,  // 1: api.admin.v1.DeptLabel.children:type_name -> api.admin.v1.DeptLabel
	13, // 2: api.admin.v1.ListDeptReply.data:type_name -> api.admin.v1.DeptTree
	13, // 3: api.admin.v1.GetDeptTreeReply.data:type_name -> api.admin.v1.DeptTree
	3,  // 4: api.admin.v1.Dept.ListDept:input_type -> api.admin.v1.ListDeptRequest
	5,  // 5: api.admin.v1.Dept.GetDeptTree:input_type -> api.admin.v1.GetDeptTreeRequest
	7,  // 6: api.admin.v1.Dept.CreateDept:input_type -> api.admin.v1.CreateDeptRequest
	9,  // 7: api.admin.v1.Dept.UpdateDept:input_type -> api.admin.v1.UpdateDeptRequest
	11, // 8: api.admin.v1.Dept.DeleteDept:input_type -> api.admin.v1.DeleteDeptRequest
	0,  // 9: api.admin.v1.Dept.RoleDeptTreeSelect:input_type -> api.admin.v1.RoleDeptTreeSelectRequest
	4,  // 10: api.admin.v1.Dept.ListDept:output_type -> api.admin.v1.ListDeptReply
	6,  // 11: api.admin.v1.Dept.GetDeptTree:output_type -> api.admin.v1.GetDeptTreeReply
	8,  // 12: api.admin.v1.Dept.CreateDept:output_type -> api.admin.v1.CreateDeptReply
	10, // 13: api.admin.v1.Dept.UpdateDept:output_type -> api.admin.v1.UpdateDeptReply
	12, // 14: api.admin.v1.Dept.DeleteDept:output_type -> api.admin.v1.DeleteDeptReply
	1,  // 15: api.admin.v1.Dept.RoleDeptTreeSelect:output_type -> api.admin.v1.RoleDeptTreeSelectReply
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_dept_proto_init() }
func file_dept_proto_init() {
	if File_dept_proto != nil {
		return
	}
	file_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dept_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleDeptTreeSelectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleDeptTreeSelectReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeptLabel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDeptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDeptReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeptTreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeptTreeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDeptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDeptReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDeptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDeptReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDeptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dept_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDeptReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dept_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dept_proto_goTypes,
		DependencyIndexes: file_dept_proto_depIdxs,
		MessageInfos:      file_dept_proto_msgTypes,
	}.Build()
	File_dept_proto = out.File
	file_dept_proto_rawDesc = nil
	file_dept_proto_goTypes = nil
	file_dept_proto_depIdxs = nil
}
