// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLogLogin = "log_logins"

// LogLogin mapped from table <log_logins>
type LogLogin struct {
	ID            int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`
	Username      string         `gorm:"column:username;type:varchar(128);not null;comment:用户名" json:"username"`
	Status        int32          `gorm:"column:status;type:tinyint(2);not null;default:1;comment:1=正常 2=异常" json:"status"`
	Ipaddr        string         `gorm:"column:ipaddr;type:varchar(255);not null;comment:ip地址" json:"ipaddr"`
	LoginLocation string         `gorm:"column:login_location;type:varchar(255);not null;comment:归属地" json:"login_location"`
	Browser       string         `gorm:"column:browser;type:varchar(255);not null;comment:浏览器" json:"browser"`
	Os            string         `gorm:"column:os;type:varchar(255);not null;comment:系统" json:"os"`
	Platform      string         `gorm:"column:platform;type:varchar(255);not null;comment:固件" json:"platform"`
	CreateBy      string         `gorm:"column:create_by;type:varchar(128);not null;comment:创建人" json:"create_by"`
	UpdateBy      string         `gorm:"column:update_by;type:varchar(128);not null;comment:更新者" json:"update_by"`
	Remark        string         `gorm:"column:remark;type:varchar(255);not null;comment:备注" json:"remark"`
	Msg           string         `gorm:"column:msg;type:varchar(255);not null;comment:消息" json:"msg"`
	LoginTime     time.Time      `gorm:"column:login_time;type:timestamp;comment:登录时间" json:"login_time"`
	CreatedAt     time.Time      `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`
}

// TableName LogLogin's table name
func (*LogLogin) TableName() string {
	return TableNameLogLogin
}
