// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLogJob = "log_jobs"

// LogJob mapped from table <log_jobs>
type LogJob struct {
	ID           int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`
	Name         string         `gorm:"column:name;type:varchar(128);not null;comment:任务名称" json:"name"`
	JobGroup     string         `gorm:"column:job_group;type:varchar(128);not null;comment:分组" json:"job_group"`
	EntryID      int32          `gorm:"column:entry_id;type:int(11);not null;comment:任务id" json:"entry_id"`
	InvokeTarget string         `gorm:"column:invoke_target;type:varchar(128);not null;comment:调用方法" json:"invoke_target"`
	LogInfo      string         `gorm:"column:log_info;type:varchar(255);not null;comment:日志信息" json:"log_info"`
	Status       int32          `gorm:"column:status;type:tinyint(2);not null;default:1;comment:1=正常 2=异常" json:"status"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`
}

// TableName LogJob's table name
func (*LogJob) TableName() string {
	return TableNameLogJob
}
