// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysMenuBtn = "sys_menu_btns"

// SysMenuBtn mapped from table <sys_menu_btns>
type SysMenuBtn struct {
	ID     int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`
	MenuID int64  `gorm:"column:menu_id;type:bigint(20);not null;comment:菜单ID" json:"menu_id"`
	Name   string `gorm:"column:name;type:varchar(191);not null;comment:按钮关键key" json:"name"`
	Desc   string `gorm:"column:desc;type:varchar(191);not null;comment:按钮描述" json:"desc"`
}

// TableName SysMenuBtn's table name
func (*SysMenuBtn) TableName() string {
	return TableNameSysMenuBtn
}
