// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRoleMenu = "sys_role_menus"

// SysRoleMenu mapped from table <sys_role_menus>
type SysRoleMenu struct {
	ID       int64  `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:主键id" json:"id"`
	RoleID   int64  `gorm:"column:role_id;type:bigint(20);not null;comment:角色id" json:"role_id"`
	MenuID   int64  `gorm:"column:menu_id;type:bigint(20);not null;comment:菜单id" json:"menu_id"`
	RoleName string `gorm:"column:role_name;type:varchar(128);not null;comment:角色名称" json:"role_name"`
}

// TableName SysRoleMenu's table name
func (*SysRoleMenu) TableName() string {
	return TableNameSysRoleMenu
}
