// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysDiscovery = "sys_discovery"

// SysDiscovery mapped from table <sys_discovery>
type SysDiscovery struct {
	ID      int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name    string `gorm:"column:name;type:varchar(255);comment:名称" json:"name"`
	Picture string `gorm:"column:picture;type:varchar(255);comment:发现页图片" json:"picture"`
	Rank    int32  `gorm:"column:rank;type:int(11);default:1;comment:排序" json:"rank"`
	Link    string `gorm:"column:link;type:varchar(255);comment:发现页链接" json:"link"`
	Status  int32  `gorm:"column:status;type:int(11);default:1;comment:发现页状态, 1-正常，2-异常" json:"status"`
}

// TableName SysDiscovery's table name
func (*SysDiscovery) TableName() string {
	return TableNameSysDiscovery
}
